files: \.(json|py)$
repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: pretty-format-json
      args:
      - "--autofix"
      - "--no-ensure-ascii"
      - "--indent=4"
      - "--no-sort-keys"

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.228
    hooks:
    - id: ruff
      args: [--fix, --target-version, "py311", --extend-select, "I", --extend-ignore, "F841,E501"]

-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
    - id: add-trailing-comma
